### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by opieces** [Popov72/OceanDemo#2]
hello，Popov
Great project, I've been following this project for a few months and it worked well, however recently, when I open the example, browser shows white screen without any error report, but gui form is displayed well, including Demo, Playground and main version。

os:win10  
graphics card:3080ti
browser:Google Chrome 108.0.5355.0  canary （64 bit） (cohort: Clang-64) and  Microsoft Edge | 108.0.1433.0 canary (64 bit)
babylonjs:5.8.0
note:Unsafe WebGPU Enabled

Look forward to your favourable reply

**Comment by Popov72** [comment]
Yes, the spec/the implementation have evolved and we need to cope with them.

I have already created an issue for that (https://github.com/BabylonJS/Babylon.js/issues/13066) so I'm closing this one.
